### ISSUE TITLE
[PATCH] add configure.ac --with-liblzma switch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jmacd/xdelta#178]
```
Hi,

See provided patch.

Regards,
Matthieu
```

Original issue reported on code.google.com by `mcra...@gmail.com` on 12 May 2014 at 9:33

Attachments:
* [0001-xdelta3-add-with-liblzma-configure-option.patch](https://storage.googleapis.com/google-code-attachments/xdelta/issue-178/comment-0/0001-xdelta3-add-with-liblzma-configure-option.patch)

**Comment by jmacd** [comment]
Oops. I forgot to apply this for 3.0.9. Sorry--

**Comment by jmacd** [comment]
https://github.com/jmacd/xdelta-devel/commit/adcba8bb76667f648fbeac099ad1f014a781b228
