### ISSUE TITLE
xdelta 3.0.10 not worked on Win7x32 SP1

### ISSUE THREAD

**Issue by usermode** [jmacd/xdelta#206]
I'm try to launch complete 3.0.10 x86-x64 exe module on Win7x32 SP1 and can't use it because it try to launch x64 stub in 32-bit system. I think that bug in OS bit detection while xdelta try to use required self module. Please fix this bug

**Comment by mgrinzPlayer** [comment]
xdelta3-x86_64-3.0.10.exe - only for 64bit Windows.
xdelta3-i686-3.0.10.exe - for both, 32bit and 64bit Windows

https://en.wikipedia.org/wiki/X86-64

**Comment by usermode** [comment]
Oh, sorry.. I'm think that xdelta3-x86_64-3.0.10.exe is a two editions in one.
