### ISSUE TITLE
Delta embeds full file names

### ISSUE THREAD

**Issue by mwisnicki** [jmacd/xdelta#259]
Is it possible to produce delta without embedding paths?

**Comment by ivan386** [comment]
> The -A flag may be used to set application-specific data in the VCDIFF header (you may view with xdelta3 printhdr). By default, the application-specific data includes the source and input filenames, as well as descriptors to help with ExternalCompression. You can disable the application header with -A=.

https://github.com/jmacd/xdelta/blob/wiki/CommandLineSyntax.md

**Comment by mwisnicki** [comment]
Thanks!
